language: python
python:
  - '2.7'
  - '3.6'
before_install:
  - nvm install $NODE_VERSION
  - npm install -g chromedriver
  - pip install virtualenv
  - pip install codecov
install:
  - make setup
script:
  - make test
  - test $TRAVIS_BRANCH = "master" &&
    codecov
