language: python
python:
  - '2.7'
  - '3.6'
env:
  - NODE_VERSION="8"
before_install:
  - nvm install $NODE_VERSION
  - npm install -g chromedriver
  - pip install virtualenv
  - pip install codecov
addons:
  chrome: stable
install:
  - make setup
script:
  - make app
  - make test
  - test $TRAVIS_BRANCH = "master" &&
    codecov
